version: '3.7'
services:
  app:
    container_name: docker-web_sockets
    restart: always
    volumes:
      - .:/usr/src/app
    build: .
    command: |
      npm run start &
      npm run start:dev
    ports:
      - '4000:4000'
      - '8080:8080'
